apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: three-tier
data:
  DB_HOST: "three-tier-mysql.ctoa2kqsa984.ap-south-1.rds.amazonaws.com"
  DB_USER: "appuser"
  DB_DATABASE: "transactions"
